# Generated by Django 5.0 on 2024-02-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complexity',
            field=models.IntegerField(default=0, verbose_name='complexity'),
        ),
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='duration'),
        ),
    ]
